# Generated by Django 4.2.1 on 2023-05-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvdbseries",
            name="season_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
