# Generated by Django 4.2.1 on 2023-05-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0003_association"),
    ]

    operations = [
        migrations.CreateModel(
            name="TvdbRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
