# Generated by Django 4.2.1 on 2023-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0004_tvdbrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=200)),
            ],
        ),
    ]
