# Generated by Django 4.2.1 on 2023-05-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0005_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeriesConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("match_expression", models.CharField(max_length=100)),
                ("settings", models.TextField()),
                (
                    "njpw_world_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sonarr.njpwworldseries",
                    ),
                ),
                (
                    "tvdb_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sonarr.tvdbseries",
                    ),
                ),
            ],
        ),
    ]
