# Generated by Django 4.2.1 on 2023-05-16 23:34

from django.db import migrations
import django_yaml_field.fields


class Migration(migrations.Migration):

    replaces = [
        ("sonarr", "0008_alter_association_options_and_more"),
        ("sonarr", "0009_remove_seriesconfiguration_settings"),
        ("sonarr", "0010_seriesconfiguration_settings"),
    ]

    dependencies = [
        ("sonarr", "0007_cookie_alter_seriesconfiguration_settings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={
                "ordering": ["tvdb_episode__series__id", "tvdb_episode__air_date"]
            },
        ),
        migrations.AlterModelOptions(
            name="njpwworldepisode",
            options={"ordering": ["series__id", "air_date"]},
        ),
        migrations.AlterModelOptions(
            name="tvdbepisode",
            options={"ordering": ["series__id", "air_date"]},
        ),
        migrations.RemoveField(
            model_name="seriesconfiguration",
            name="settings",
        ),
        migrations.AddField(
            model_name="seriesconfiguration",
            name="settings",
            field=django_yaml_field.fields.YAMLField(blank=True, null=True),
        ),
    ]
