# Generated by Django 4.2.1 on 2023-05-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0008_alter_association_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seriesconfiguration",
            name="settings",
        ),
    ]
