# Generated by Django 4.2.1 on 2023-05-16 23:32

from django.db import migrations
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0009_remove_seriesconfiguration_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesconfiguration",
            name="settings",
            field=django_yaml_field.fields.YAMLField(blank=True, null=True),
        ),
    ]
