# Generated by Django 4.2.1 on 2023-05-16 23:35

from django.db import migrations
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "sonarr",
            "0008_alter_association_options_and_more_squashed_0010_seriesconfiguration_settings",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="seriesconfiguration",
            name="settings",
            field=django_yaml_field.fields.YAMLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
