# Generated by Django 4.2.1 on 2023-07-31 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0011_alter_seriesconfiguration_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="associated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="njpwworldepisode",
            name="downloaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
