# Generated by Django 4.2.1 on 2023-09-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sonarr", "0013_alter_njpwworldepisode_downloaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="njpwworldepisode",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="njpwworldepisode",
            name="series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sonarr.njpwworldseries",
            ),
        ),
    ]
